"use client";
import { useState } from "react";
import { submitLead } from "../services/contactService";
import type { LeadType } from "../types/lead";

interface ContactFormProps { type?: LeadType; propertyId?: string; title?: string; valuation?: boolean; }
export function ContactForm({ type = "contact", propertyId, title = "Cuéntanos cómo podemos ayudarte", valuation = false }: ContactFormProps) {
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const [error, setError] = useState("");
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!form.get("name") || !form.get("email") || !form.get("privacy")) { setError("Completa los campos obligatorios y acepta la política de privacidad."); return; } setError(""); setStatus("sending"); try { await submitLead({ type, propertyId, name: String(form.get("name")), lastName: String(form.get("lastName") || ""), email: String(form.get("email")), phone: String(form.get("phone") || ""), message: String(form.get("message") || ""), contactType: String(form.get("reason") || ""), source: "website", metadata: valuation ? { propertyType: String(form.get("propertyType")), location: String(form.get("location")), surface: String(form.get("surface")) } : undefined }); setStatus("sent"); event.currentTarget.reset(); } catch { setStatus("error"); } };
  if (status === "sent") return <div className="form-success"><span>✓</span><h3>Gracias por escribirnos</h3><p>Hemos recibido tu solicitud. Te contactaremos muy pronto.</p><button onClick={() => setStatus("idle")}>Enviar otra consulta</button></div>;
  return <form className="contact-form" onSubmit={submit}><h2>{title}</h2><div className="form-grid"><label>Nombre*<input name="name" autoComplete="given-name" required /></label><label>Apellidos<input name="lastName" autoComplete="family-name" /></label><label>Email*<input name="email" type="email" autoComplete="email" required /></label><label>Teléfono<input name="phone" type="tel" autoComplete="tel" /></label>{valuation && <><label>Tipo de inmueble<select name="propertyType"><option>Piso</option><option>Casa</option><option>Chalet</option><option>Ático</option><option>Terreno</option></select></label><label>Zona o población<select name="location"><option>Cubelles</option><option>Vilanova i la Geltrú</option><option>Sitges</option><option>Cunit</option></select></label><label>Superficie aproximada<input name="surface" type="number" placeholder="m²" /></label><label>Habitaciones<select name="bedrooms"><option>1</option><option>2</option><option>3</option><option>4+</option></select></label></>} {!valuation && <label className="full">Motivo<select name="reason"><option>Comprar vivienda</option><option>Vender vivienda</option><option>Solicitar valoración</option><option>Otra consulta</option></select></label>}<label className="full">Mensaje<textarea name="message" rows={4} placeholder={valuation ? "[Añade aquí cualquier información útil sobre la vivienda]" : "[Escribe aquí tu consulta]"} /></label></div><label className="privacy"><input name="privacy" type="checkbox" required /> <span>He leído y acepto la política de privacidad.*</span></label>{error && <p className="form-error">{error}</p>}{status === "error" && <p className="form-error">No hemos podido enviar tu consulta. Comprueba la conexión con Supabase e inténtalo de nuevo.</p>}<button className="button-dark" disabled={status === "sending"}>{status === "sending" ? "Enviando..." : valuation ? "Solicitar valoración" : "Enviar consulta"} <span>→</span></button></form>;
}
